# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='by_user_name',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='total_upvote',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='story_link',
        ),
        migrations.AddField(
            model_name='news',
            name='hn_user',
            field=models.CharField(default='rt', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
