# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170923_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn_user', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('age', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('is_reply', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('parent_comment', models.BigIntegerField(default=0)),
                ('show_on_site', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
