# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
    ]
