# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170923_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id', 'created_time']},
        ),
    ]
