# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20170923_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='story_link',
            new_name='story_text',
        ),
        migrations.AlterField(
            model_name='news',
            name='total_comments',
            field=models.CharField(max_length=50),
        ),
    ]
