# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20170924_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link_href',
            field=models.CharField(default='we', max_length=255),
            preserve_default=False,
        ),
    ]
