# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20170925_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['parent_comment__id']},
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_nested_level',
            field=models.IntegerField(default=0),
        ),
    ]
