# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20170926_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
    ]
