# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_upvotecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_crawled',
            field=models.BooleanField(default=True),
        ),
    ]
