# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_news_is_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hn_id_code',
            field=models.CharField(default='222', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
