# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20171001_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['rank', 'created_time']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='news',
            name='latest_created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
