# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20171001_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_crawled',
            field=models.BooleanField(default=True),
        ),
    ]
