# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_comment_is_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hn_id_code',
            field=models.CharField(default='111', max_length=150),
            preserve_default=False,
        ),
    ]
