# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_comment_hn_id_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['rank', '-created_time']},
        ),
        migrations.AddField(
            model_name='news',
            name='page',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
