# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20171002_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
